#Documentation config
springDoc:
  #Json documentation
  apiDocs:
    enabled: true
    path: /api/v3/api-docs
  #Swagger documentation
  swaggerUi:
    enabled: true
    path: /doc/swagger-ui.html
spring:
  application:
    name: OpenAIAssistantAPI
    description: API REST diseñada para implementar y facilitar el uso de la API de OpenAI en un sistema de chat basado en texto. Permite interactuar con el sistema de chat mediante dos endpoints principales.
    version: 1.0.0
  #Open ai config
  ai:
    openai:
      apiKey: ${SPRING_AI_OPENAI_APIKEY} #Tu clave API de Open Ai
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
server:
  servlet:
    encoding:
      forceResponse: true
      charset: UTF-8